# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

blueprint:
  name: Simple Vacancy Light Control
  description: Turn off a light if no motion is detected after it's turned on, with optional reactivation
  domain: automation
  source_url: https://github.com/madbrain76/Home-assistant-misc/vacancy-switch.yaml

  input:
    light:
      name: Light
      description: Light entity to control
      selector:
        entity:
          domain: light

    motion_sensor:
      name: Motion Sensor
      description: Motion sensor entity to monitor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    timeout:
      name: Deactivation timeout
      description: How long to wait for motion before turning off the light
      selector:
        duration:
      default:
        minutes: 5

    reactivation_timeout:
      name: Reactivation timeout
      description: How long after this automation turned off the light to allow reactivation if motion is detected
      selector:
        duration:
      default:
        seconds: 30

variables:
  light_entity: !input light
  motion_entity: !input motion_sensor

trigger:
  - platform: homeassistant
    event: start
    id: ha_start

  - platform: event
    event_type: automation_reloaded
    id: automation_reload

  - platform: state
    entity_id: !input light
    to: "on"
    id: light_on

  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for: !input timeout
    id: motion_cleared

mode: single

action:
  - choose:
      # HA start/reload OR light turned on externally: wait for motion
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: or
                    conditions:
                      - condition: trigger
                        id: ha_start
                      - condition: trigger
                        id: automation_reload
                  - condition: state
                    entity_id: !input light
                    state: "on"
                  - condition: state
                    entity_id: !input motion_sensor
                    state: "off"
              - condition: and
                conditions:
                  - condition: trigger
                    id: light_on
                  - condition: state
                    entity_id: !input motion_sensor
                    state: "off"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensor
                to: "on"
            timeout: !input timeout
            continue_on_timeout: true
          - if:
              - condition: template
                value_template: "{{ wait.trigger is none }}"
            then:
              - service: light.turn_off
                target:
                  entity_id: !input light
              # Reactivation window: wait for motion
              - wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensor
                    to: "on"
                timeout: !input reactivation_timeout
                continue_on_timeout: true
              # If motion detected, reactivate
              - if:
                  - condition: template
                    value_template: "{{ wait.trigger is not none and wait.trigger.to_state.state == 'on' }}"
                then:
                  - service: light.turn_on
                    target:
                      entity_id: !input light

      # Motion cleared and stayed off for deactivation timeout duration : turn off the light
      - conditions:
          - condition: trigger
            id: motion_cleared
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light
          # Reactivation window: wait for motion
          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensor
                to: "on"
            timeout: !input reactivation_timeout
            continue_on_timeout: true
          # If motion detected, reactivate
          - if:
              - condition: template
                value_template: "{{ wait.trigger is not none and wait.trigger.to_state.state == 'on' }}"
            then:
              - service: light.turn_on
                target:
                  entity_id: !input light
