# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

blueprint:
  name: Simple Vacancy Light Control
  description: Turn off a light if no motion is detected after it's turned on
  domain: automation
  source_url: https://github.com/madbrain76/Home-assistant-misc/vacancy-switch.yaml

  input:
    light:
      name: Light
      description: Light entity to control
      selector:
        entity:
          domain: light

    motion_sensor:
      name: Motion Sensor
      description: Motion sensor entity to monitor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    timeout:
      name: Deactivation Timeout
      description: How long to wait for motion before turning off the light
      selector:
        duration:
      default:
        minutes: 5

trigger:
  - platform: state
    entity_id: !input light
    to: "on"
    id: light_on

  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for: !input timeout
    id: motion_clear

action:
  - if:
      - condition: trigger
        id: motion_clear
    then:
      - service: light.turn_off
        target:
          entity_id: !input light
