# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

blueprint:
  name: Simple Vacancy Light Control
  description: Turn off a light if no motion is detected after it's turned on
  domain: automation
  source_url: https://github.com/madbrain76/Home-assistant-misc/vacancy-switch.yaml

  input:
    light:
      name: Light
      description: Light entity to control
      selector:
        entity:
          domain: light

    motion_sensor:
      name: Motion Sensor
      description: Motion sensor entity to monitor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    timeout:
      name: Timeout
      description: How long to wait for motion before turning off the light
      selector:
        duration:
      default:
        minutes: 5

    reactivation_timeout:
      name: Reactivation Timeout
      description: How long to wait for motion after turning off the light to reactivate it
      selector:
        duration:
      default:
        minutes: 1

trigger:
  - platform: homeassistant
    event: start
    id: ha_start

  - platform: event
    event_type: automation_reloaded
    id: automation_reload

  - platform: state
    entity_id: !input light
    to: "on"
    id: light_on

  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for: !input timeout
    id: motion_clear

mode: single

variables:
  light_entity: !input light
  motion_entity: !input motion_sensor
  timeout: !input timeout
  reactivation_timeout: !input reactivation_timeout

action:
  - service: system_log.write
    data:
      message: "VACANCY: trigger={{ trigger.id }}, light={{ states[light_entity] }}, motion={{ states[motion_entity] }}"
      level: warning

  # Case 1: HA start/reload or light turned on - wait for motion first
  - if:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: ha_start
                  - condition: trigger
                    id: automation_reload
              - condition: state
                entity_id: !input light
                state: "on"
              - condition: state
                entity_id: !input motion_sensor
                state: "off"
          - condition: and
            conditions:
              - condition: trigger
                id: light_on
              - condition: state
                entity_id: !input motion_sensor
                state: "off"
    then:
      - service: system_log.write
        data:
          message: "CASE1: Waiting for motion with timeout {{ timeout }}"
          level: warning
      - wait_for_trigger:
          - platform: state
            entity_id: !input motion_sensor
            to: "on"
        timeout: !input timeout
        continue_on_timeout: true
      - service: system_log.write
        data:
          message: "CASE1: wait complete, motion_detected={{ wait.trigger is not none }}"
          level: warning

  # Case 2: Turn off light (runs if motion_clear OR if Case 1 timed out)
  - if:
      - condition: or
        conditions:
          - condition: trigger
            id: motion_clear
          - condition: template
            value_template: "{{ trigger.id != 'light_on' or (trigger.id == 'light_on' and wait is defined and wait.trigger is none) }}"
    then:
      - service: system_log.write
        data:
          message: "CASE2: Turning off light"
          level: warning
      - service: light.turn_off
        target:
          entity_id: !input light

      # Case 3: Wait for motion during reactivation timeout to reactivate light
      - service: system_log.write
        data:
          message: "CASE3: Waiting for motion during reactivation timeout {{ reactivation_timeout }}"
          level: warning
      - wait_for_trigger:
          - platform: state
            entity_id: !input motion_sensor
            to: "on"
        timeout: !input reactivation_timeout
        continue_on_timeout: true
      - service: system_log.write
        data:
          message: "CASE3: reactivation wait complete, motion_detected={{ wait.trigger is not none }}"
          level: warning
      
      # Case 4: Reactivate light if motion detected during reactivation timeout
      - if:
          - condition: template
            value_template: "{{ wait.trigger is not none }}"
        then:
          - service: system_log.write
            data:
              message: "CASE4: Motion detected, reactivating light"
              level: warning
          - service: light.turn_on
            target:
              entity_id: !input light
