# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# This automation mimicks the behavior of California Title 24 compliant hard-wired vacancy
# "dumb" switches, but is compatible with smart light bulbs.
#
# Traditional vacancy switches, such as the Leviton IPP15/IPP0R series, have a relay which 
# always cuts power to the load eventually, with the only possibility of turning it back on 
# being a physical press of the switch.
#
# Unfortunately, the maximum deactivation timeout on these units is 30 minutes, configurable
# by physical setting inside the switch. The deactivation behavior cannot be disabled entirely.
# This makes these switches completely incompatible with smart bulbs.
#
# The rationale for the reactivation timeout is imperfect motion sensor coverage, or long
# periods of undetected motion, which can result in unwanted deactivation. For example, reading a
# book or using a phone while not moving much might go undetected. In this case, if the lights
# turn off, one can quickly move (for example by waving hands) in range of the motion sensor.
# This will automatically reactivate the light if done within the reactivation timeout period.
# Without this reactivation timeout, the light would need to be manually turned back on, which
# would typically require physically walking to a switch in complete darkness, potentially unsafe.
#
# Implementation uses Zooz ZEN76/ZEN75 Z-wave switches configured with power relay always on,
# allowing smart bulbs to remain on the network and controllable by Home Assistant automations.
# The switches are used solely as scene controllers. This means smart lights are then exclusively
# controllable by HA automations, such as this one.
#
# The motion sensors used are Yolink 7804 with local hub and Matter integration. As of this
# writing, there are issues with the local hub including problems with inconsistent device
# addition and motion state going unreported on new devices. Workarounds include deletion of
# devices from both local and cloud, then power cycling the hub with a 10 second wait before
# restoring power. The hub will hang indefinitely without the delay. The backup battery must
# be removed for this workaround to work. These issues are absent when using the Yolink
# cloud integration instead.
#
# Other automations are used for scene controller presses (Z-Wave JS) and infrared remote control.
# For IR, an ARRX18G universal remote is programmed with Remote Master and used with an
# AtHom AR-01 Wifi IR receiver/blaster.

blueprint:
  name: Vacancy switch state machine implementation
  description: >
    Smart occupancy-based light automation. Light must be manually turned on.
    Automatically turns off if no motion detected within timeout. Optionally reactivates
    if motion detected within reactivation window.
  domain: automation
  source_url: https://github.com/madbrain76/Home-assistant-misc/vacancy-switch.yaml

  input:
    light:
      name: Light
      description: Light entity to control
      selector:
        entity:
          domain: light

    motion_sensor:
      name: Motion or Occupancy Sensor
      description: Motion or occupancy sensor entity to monitor
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy

    timeout:
      name: Timeout
      description: How long motion must be absent before turning off the light
      selector:
        duration:
      default:
        minutes: 5

    reactivation_timeout:
      name: Reactivation Timeout
      description: How long to wait for motion after this automation turns off the light to reactivate it
      selector:
        duration:
      default:
        seconds: 30

trace:
  stored_traces: 50

triggers:
  - trigger: homeassistant
    event: start
    id: ha_start

  - trigger: event
    event_type: automation_reloaded
    id: automation_reload

mode: single

variables:
  light_entity: !input light
  motion_entity: !input motion_sensor
  timeout_duration: !input timeout
  reactivation_timeout_duration: !input reactivation_timeout

actions:
  # - action: system_log.write
  #   data:
  #     message: "VACANCY: Started by {{ trigger.id }}, light is {{ states[light_entity].state }}"
  #     level: debug

  # Initialize state: if light is on at startup/reload, treat as externally turned on
  - variables:
      phase: "{% if states[light_entity].state == 'on' %}deactivation{% else %}waiting{% endif %}"
      light_external_on_time: "{% if states[light_entity].state == 'on' %}{{ now() }}{% endif %}"
      light_automation_off_time: null
      light_reactivated_time: null

  # - action: system_log.write
  #   data:
  #     message: "VACANCY: Initial phase={% if states[light_entity].state == 'on' %}deactivation (light was on){% else %}waiting (light was off){% endif %}"
  #     level: debug

  # Main state machine loop (infinite until automation stops)
  - repeat:
      until: "{{ false }}"
      sequence:
        # PHASE: WAITING - Light is off, waiting for external turn-on
        - if:
            - condition: template
              value_template: "{{ phase == 'waiting' }}"
          then:
            # - action: system_log.write
            #   data:
            #     message: "VACANCY PHASE: WAITING (light off, waiting for external on)"
            #     level: debug

            # Check if light is already on (shouldn't happen but defensive)
            - if:
                - condition: template
                  value_template: "{{ states[light_entity].state == 'on' }}"
              then:
                - variables:
                    phase: "deactivation"
                    light_external_on_time: "{{ now() }}"
                # - action: system_log.write
                #   data:
                #     message: "VACANCY: Light is already on in WAITING phase, transitioning to DEACTIVATION"
                #     level: debug
              else:
                # Light is off, wait for external turn-on
                - wait_for_trigger:
                    - trigger: state
                      entity_id: !input light
                      to: "on"
                      id: light_on_external
                  continue_on_timeout: true

                - if:
                    - condition: template
                      value_template: "{{ wait.trigger is not none }}"
                  then:
                    - variables:
                        phase: "deactivation"
                        light_external_on_time: "{{ now() }}"
                    # - action: system_log.write
                    #   data:
                    #     message: "VACANCY: Light turned on externally at {{ light_external_on_time }}"
                    #     level: debug

        # PHASE: DEACTIVATION - Light is on, waiting for motion to clear for timeout OR external turn-off
        - if:
            - condition: template
              value_template: "{{ phase == 'deactivation' }}"
          then:
            # - action: system_log.write
            #   data:
            #     message: "VACANCY PHASE: DEACTIVATION (light on, waiting {{ timeout_duration }} with no motion or external off)"
            #     level: debug

            - wait_for_trigger:
                # Trigger if motion stays off for entire timeout duration
                - trigger: state
                  entity_id: !input motion_sensor
                  to: "off"
                  for: !input timeout
                  id: motion_clear_timeout

                # Trigger if light is externally turned off
                - trigger: state
                  entity_id: !input light
                  to: "off"
                  id: light_off_external
              continue_on_timeout: true

            - if:
                - condition: template
                  value_template: "{{ wait.trigger is not none }}"
              then:
                # Motion cleared for timeout duration - turn off light and enter reactivation
                - if:
                    - condition: template
                      value_template: "{{ wait.trigger.id == 'motion_clear_timeout' }}"
                  then:
                    # - action: system_log.write
                    #   data:
                    #     message: "VACANCY: Motion absent for {{ timeout_duration }}, turning off light"
                    #     level: debug
                    - action: light.turn_off
                      target:
                        entity_id: !input light
                    - variables:
                        phase: "reactivation"
                        light_automation_off_time: "{{ now() }}"

                # Light turned off externally - go back to waiting
                - if:
                    - condition: template
                      value_template: "{{ wait.trigger.id == 'light_off_external' }}"
                  then:
                    # - action: system_log.write
                    #   data:
                    #     message: "VACANCY: Light turned off externally, returning to WAITING"
                    #     level: debug
                    - variables:
                        phase: "waiting"
                        light_external_on_time: null
                        light_automation_off_time: null
                        light_reactivated_time: null

        # PHASE: REACTIVATION - Light is off (we turned it off), waiting for motion or timeout
        - if:
            - condition: template
              value_template: "{{ phase == 'reactivation' }}"
          then:
            # - action: system_log.write
            #   data:
            #     message: "VACANCY PHASE: REACTIVATION (light off, waiting {{ reactivation_timeout_duration }} for motion)"
            #     level: debug

            - wait_for_trigger:
                # Trigger if motion detected
                - trigger: state
                  entity_id: !input motion_sensor
                  to: "on"
                  id: motion_on_reactivation

                # Trigger if light is externally turned on
                - trigger: state
                  entity_id: !input light
                  to: "on"
                  id: light_on_external_reactivation
              timeout: !input reactivation_timeout
              continue_on_timeout: true

            - if:
                - condition: template
                  value_template: "{{ wait.trigger is not none }}"
              then:
                # Motion detected during reactivation window - turn on light
                - if:
                    - condition: template
                      value_template: "{{ wait.trigger.id == 'motion_on_reactivation' }}"
                  then:
                    # - action: system_log.write
                    #   data:
                    #     message: "VACANCY: Motion detected during reactivation, turning light on"
                    #     level: debug
                    - action: light.turn_on
                      target:
                        entity_id: !input light
                    - variables:
                        phase: "deactivation"
                        light_reactivated_time: "{{ now() }}"

                # Light turned on externally during reactivation - go to deactivation
                - if:
                    - condition: template
                      value_template: "{{ wait.trigger.id == 'light_on_external_reactivation' }}"
                  then:
                    # - action: system_log.write
                    #   data:
                    #     message: "VACANCY: Light turned on externally during reactivation"
                    #     level: debug
                    - variables:
                        phase: "deactivation"
                        light_external_on_time: "{{ now() }}"
              else:
                # Reactivation timeout elapsed, no motion - go back to waiting
                # - action: system_log.write
                #   data:
                #     message: "VACANCY: Reactivation timeout elapsed, returning to WAITING"
                #     level: debug
                - variables:
                    phase: "waiting"
                    light_automation_off_time: null
                    light_reactivated_time: null
